### ISSUE TITLE
Access current file name/path in custom rule

### ISSUE THREAD

**Issue by WickyNilliams** [birjolaxew/svglint#30]
Is there some way to access the name/path for the current file in a custom rule? It doesn't seem to be available on any of the arguments passed to the function.

**Comment by WickyNilliams** [comment]
Seems like you could add a 4th `info` param like:

```js
rule(reporter, cheerioParsed, ast, { path: this.path })
```

https://github.com/birjolaxew/svglint/blob/bfbc47ab9d16872aa9c6fc05684eab530723d405/src/lib/linting.js#L108

**Comment by birjolaxew** [comment]
As mentioned in another issue (#11) I'm unfortunately unable to dedicate any real time to svglint. I'll have a bit of time at the end of the month, but otherwise plan to rewrite the programmatic interface a fair bit once my schedule clears up in a few months.

If you'd like this before then, I'd be happy to review a PR.

**Comment by WickyNilliams** [comment]
No worries, I completely understand that your time is limited and open source often has to take a backseat!

I'll see if i can whip up a PR. Should be pretty easy if you're happy with the approach i outlined above?

**Comment by birjolaxew** [comment]
Sounds good. Your approach seems reasonable, I'd be happy with it in a PR (plus a test to avoid regressions during the later rewrite).
