### ISSUE TITLE
Add support for checking line-break

### ISSUE THREAD

**Issue by LitoMore** [birjolaxew/svglint#45]
Related to https://github.com/simple-icons/simple-icons/pull/6880

**Comment by ericcornelissen** [comment]
I don't think SVGLint is the right tool for this. Mostly because it's neither specific to SVGs (other files also benefit from normalized line endings) nor directly relevant to SVGs (the SVGs validity, in general, is not affected by the line endings used).

That said, If you feel strongly that this is something that SVGLint should be able to check for, you can always publish a plugin to npm for it. as far as I can tell you've got everything you need to do that already and if not we can work on improving SVGLint to make it possible. But I'd advise looking for alternative tools (e.g. EditorConfig+EditorConfig-checker) first.

Alternatively, a simpler solution could be just add a (new) custom rule to the SVGLint config file for simple-icons.
